class CaptionTrack {
  final String url;
  final String languageCode;
  final bool isAutoGenerated;
  final bool isTranslatable;

  const CaptionTrack({
    required this.url,
    required this.languageCode,
    required this.isAutoGenerated,
    required this.isTranslatable,
  });

  factory CaptionTrack.fromJson(Map<String, dynamic> json) {
    return CaptionTrack(
      url: (json['baseUrl'] as String).replaceAll('&fmt=srv3', ''),
      languageCode: json['languageCode'] as String,
      isAutoGenerated: json['kind'] == 'asr',
      isTranslatable: json['isTranslatable'] ?? false,
    );
  }
}